name: Windows DVWA Security Scan

on: 
  push

jobs:
  scan:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Trivy
        run: |
          Invoke-WebRequest -Uri "https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.0_Windows-64bit.zip" -OutFile "trivy.zip"
          Expand-Archive -Path "trivy.zip" -DestinationPath "C:\trivy"
          echo "C:\trivy" | Out-File -Append -Encoding ASCII $env:GITHUB_PATH

      - name: Pull DVWA Docker Image
        run: docker pull vulnerables/web-dvwa

      - name: Scan DVWA with Trivy
        run: trivy image vulnerables/web-dvwa --severity HIGH,CRITICAL
